model_path:
    prefill_model: ["/path/to/baichuan2_13b_pa_models/output/mindir_full_checkpoint/rank_0_graph.mindir"]
    decode_model: ["/path/to/baichuan2_13b_pa_models/output/mindir_inc_checkpoint/rank_0_graph.mindir"]
    argmax_model: "/path/to/serving_dev/extends_13b/argmax.mindir"
    topk_model: "/path/to/serving_dev/extends_13b/topk.mindir"
    prefill_ini: ["/path/to/baichuan2_13b_pa_models/ini/910b_default_prefill.cfg"]
    decode_ini: ["/path/to/baichuan2_13b_pa_models/ini/910_inc.cfg"]
    post_model_ini: "/path/to/baichuan2/config/config.ini"

model_config:
    model_name: 'baichuan2pa'
    max_generate_length: 4096
    end_token: 2
    seq_length: [4096] # [1024,2048,4096]
    vocab_size: 125696
    prefill_batch_size: [1]
    decode_batch_size: [1]  # [22]
    zactivate_len: [4096]
    model_type: 1
    page_attention: True   # check
    current_index: False

serving_config:
    agent_ports: [61160]
    start_device_id: 0
    server_ip: 'localhost'
    server_port: 61170

pa_config:
    num_blocks: 260
    block_size: 128
    decode_seq_length: 4096

tokenizer:
    type: BaichuanTokenizer
    vocab_file: '/path/to/baichuan2_13b_pa_models/tokenizer.model'

basic_inputs:
    type: LlamaBasicInputs

extra_inputs:
    type: LlamaExtraInputs

warmup_inputs:
    type: LlamaWarmupInputs